### ISSUE TITLE
@EmbeddedKafka does not work in projects without scala dependency

### ISSUE THREAD

**Issue by amvi23** [spring-projects/spring-kafka#1623]
Hi,

I have several Spring Boot projects and after updating from 2.3.4 to 2.3.5 (spring-kafka 2.5.7) or also 2.3.6 (spring kafka 2.5.8) all tests with @EmbeddedKafka are failing to start due to a missing class.
All those project are using Java 11 and Groovy and spock as test framework.
My current workaround is to add scala to my test dependencies.
`
dependencies {
    ...
    testImplementation("org.scala-lang:scala-library:2.12.11")
}
`
See also StackOverflow issue where I posted my workaround: [Link](https://stackoverflow.com/questions/64669007/noclassdeffounderror-scala-math-ordering-with-spring-kafka-test-2-5-7/64697950#64697950)

**Comment by garyrussell** [comment]
This is a known problem - it is cause by Boot's prescribed version of Jackson pulling in incompatible scala libraries.

See https://github.com/spring-projects/spring-kafka/issues/1604 and https://github.com/spring-projects/spring-boot/issues/23979 for more information.

Your "workaround" is the correct solution; there is nothing we can do - blame the scala folks for making such a radical change to the class in a bug fix release.

The other solution is to upgrade to spring-kafka 2.6.3 and kafka-clients 2.6.0.

You can do that by upgrading to Boot 2.4.0, or by overriding the dependencies with Boot 2.3.x https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps
