### ISSUE TITLE
Spring Kafka 2.7.x doesn't work with Kafka Clients 2.8.0

### ISSUE THREAD

**Issue by rios0rios0** [spring-projects/spring-kafka#1987]
Hello guys.

According to the documentation ([here](https://spring.io/projects/spring-kafka)) Spring Kafka 2.7.x works with Kafka Clients until 2.8.0. But actually, isn't working.

You know that Kafka Clients until 2.8.1 has a CVE-2021-38153.
I would like to upgrade my Spring Kafka to use a version without CVE.
Could you help me to find the path for the upgrade?

Below, follow please my stack trace.
```
Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/common/record/BufferSupplier
	at kafka.log.Cleaner.<init>(LogCleaner.scala:492)
	at kafka.log.LogCleaner$CleanerThread.<init>(LogCleaner.scala:306)
	at kafka.log.LogCleaner.$anonfun$startup$2(LogCleaner.scala:155)
	at kafka.log.LogCleaner.startup(LogCleaner.scala:154)
	at kafka.log.LogManager.startup(LogManager.scala:435)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:291)
	at kafka.utils.TestUtils$.createServer(TestUtils.scala:161)
	at kafka.utils.TestUtils$.createServer(TestUtils.scala:152)
	at kafka.utils.TestUtils.createServer(TestUtils.scala)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:337)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 67 more
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.record.BufferSupplier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 79 more
```

**Comment by marcelstoer** [comment]
> The CVE in this discussion is only corrected on 2.8.1 of Kafka Clients.

No, not according to their own statements that @garyrussell linked to earlier: https://lists.apache.org/thread.html/rd9ef217b09fdefaf32a4e1835b59b96629542db57e1f63edb8b006e6%40%3Cdev.kafka.apache.org%3E

> Apache Kafka 2.7.2 is a bugfix release and 26 issues, as well as CVE-2021-38153, have been fixed since 2.7.1.

However, it is (not yet?) mentioned in their 2.7.2 RC0 release notes: https://home.apache.org/~mimaison/kafka-2.7.2-rc0/RELEASE_NOTES.html

**Comment by garyrussell** [comment]
>it is (not yet?) mentioned in their 2.7.2 RC0 r

We have no control over that here; I suggest you raise your concerns over there.

https://lists.apache.org/thread/28nbowc1yzflh88g0ybv5l1q1c37d51h

I would also refer you to https://github.com/spring-projects/spring-kafka/issues/1987#issuecomment-951002595 - this is not a problem at all for Kafka clients.

**Comment by garyrussell** [comment]
FYI, spring-kafka 2.8.0 (3.0.0 clients), 2.7.9 (2.7.2) clients and 2.6.12 (2.6.3) clients are all in maven central using kafka-clients versions that include the fix for the CVE.
