### ISSUE TITLE
M2 does not compile in 1.7 due to 1.8 annotation

### ISSUE THREAD

**Issue by backroadssoftware** [spring-projects/spring-kafka#60]
Build fails in 1.7 due to @Repeatable annotation on KafkaListener but documentation states it is 1.7 compatible.

:spring-kafka:compileJava
C:\Projects\spring-kafka\spring-kafka\src\main\java\org\springframework\kafka\annotation\KafkaListener.java:21: error: cannot find symbol
import java.lang.annotation.Repeatable;
                           ^
  symbol:   class Repeatable
  location: package java.lang.annotation
C:\Projects\spring-kafka\spring-kafka\src\main\java\org\springframework\kafka\annotation\KafkaListener.java:85: error: cannot find symbol
@Repeatable(KafkaListeners.class)
 ^
  symbol: class Repeatable
2 errors
:spring-kafka:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-kafka:compileJava'.
> Compilation failed; see the compiler error output for details.

**Comment by backroadssoftware** [comment]
Using this jdk

C:\Projects\spring-kafka>java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) Client VM (build 24.79-b02, mixed mode, sharing)

**Comment by artembilan** [comment]
Hello, @backroadssoftware !

Thank you for feedback!

That's correct.

You have to use Java 8 to compile project.
But from other hand you don't need Java 8 to run applications with `spring-kafka`.
Unknown annotations are ignored by Java.

**Comment by backroadssoftware** [comment]
Thanks for the info.
