### ISSUE TITLE
Version 1.3.1 doesn't work with Kafka Client 1.0.0

### ISSUE THREAD

**Issue by tonysparks** [spring-projects/spring-kafka#477]
Hello,

I'm attempting to use the following:

```
<dependency>
                <groupId>org.springframework.kafka</groupId>
                <artifactId>spring-kafka-test</artifactId>
                <version>1.3.1.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.kafka</groupId>
                <artifactId>spring-kafka</artifactId>
                <version>1.3.1.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>1.0.0</version>
            </dependency>
```

When I run my tests, it blows up with:

```
java.lang.NoClassDefFoundError: org/apache/kafka/common/protocol/SecurityProtocol

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.springframework.kafka.test.rule.KafkaEmbedded.createProperties(KafkaEmbedded.java:222)
```

The `org/apache/kafka/common/protocol/SecurityProtocol` was moved in the kafka `1.0.0` jar; however, `org.springframework.kafka.test.rule.KafkaEmbedded` still references it.
